spring:
  application:
    name: reborn-server
  datasource:
    url: jdbc:postgresql://localhost:5432/reborn
    username: reborn
    password: reborn
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.hyunjine.reborn: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
